package com.cogent.controller.departmentController.DTO.requestDTO;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;

import java.io.Serializable;

/**
 * @author Sauravi
 */


@Getter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ApiModel
public class DepartmentRequestDTO implements Serializable {

    @ApiModelProperty(value = "Department id i.e. auto generated by database")
    private Long id;

    @ApiModelProperty(value = "Department name should be unique")
    private String departmentName;

    @ApiModelProperty(value = "Department Code should be unique")
    private String code;

    @ApiModelProperty(value = "Y, N and D are only used")
    private Character status;

}
